### ISSUE TITLE
Support of XBox Elite 2 Controller

### ISSUE THREAD

**Issue by Erebos84** [ricardoquesada/bluepad32-arduino#1]
Hello,
is the xbox elite 2 controller supported?
It is mentioned in the nina firmware but not in your list of supported controllers.
I'm able to connect it to the "Arduino Nano RP2040 Connect", but no inputs are recognized.

I used the precompiled nina firmware v2.2.1 with Bluepad32 library for Arduino v0.99.1

{ MAKE_CONTROLLER_ID( 0x045e, 0x0b05 ), CONTROLLER_TYPE_XBoxOneController, "Xbox One Elite 2 Controller" },	// { MAKE_CONTROLLER_ID( 0x045e, 0x0b13 ), CONTROLLER_TYPE_XBoxOneController, "Xbox One Series X Controller" },	// Microsoft X-Box One Elite Series X pad (Bluetooth)

**Comment by ricardoquesada** [comment]
I don't have one to test it... the key question is: Is the Xbox One Elite Series 2 using Bluetooth (classic), or BLE?

If it uses Bluetooth (classic) then it should work.
If it uses BLE, then it won't work with v2.2.1... Adding BLE support is is my TODO list.

**Comment by Erebos84** [comment]
The controller uses Bluetooth (classic) as far as I know.

Is it possible to display the debug info of Bluepad32 via serial monitor?

**Comment by ricardoquesada** [comment]
Then it should work... I had issues before with Xbox S controller... they fail at connect time, so you might need to try a few times.

Regarding serial port, debugging could be tricky in Arduino since the ESP32 and the Arduino MCU are connected via SPI...and I'm not forwarding those messages to the Arduino MCU.

Which Arduino board are you using?

The easiest way to test whether it works, is to get one of the many ESP32 dev kits (like this one: [mini_kit]), and flash the "bluepad32-unijoysticle" firmware (not the nina one), and you will see the console.



[mini_kit]: https://www.aliexpress.com/item/32815530502.html?spm=a2g0o.productlist.0.0.505645b4SlaYgs&algo_pvid=fe1dc45e-718d-4673-b992-64e9f78cd434&algo_exp_id=fe1dc45e-718d-4673-b992-64e9f78cd434-0&pdp_ext_f=%7B%22sku_id%22%3A%2264636335038%22%7D

**Comment by Erebos84** [comment]
First I tried it with an Arduino Nano RP2040. Now I have an ESP32 with the precompiled firmware v2.2.1. 
When I want to compile the gamepad.ino example from Bluepad32-arduino library I get several error messages. 
Is there a diffrent example for the ESP32?

*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp: In static member function 'static void SpiDrv::begin()':
*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp:91:20: error: 'PINS_COUNT' was not declared in this scope
   if (SLAVERESET > PINS_COUNT) {

*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp: 100:11: error: 'NINA_GPIO0' was not declared in this scope
   pinMode(NINA_GPIO0, OUTPUT);

*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp: In static member function 'static int SpiDrv::available()':
*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp:66:22: error: 'NINA_GPIO0' was not declared in this scope
 #define NINA_GPIOIRQ NINA_GPIO0
 
*\Arduino\libraries\Bluepad32\src\utility\spi_drv.cpp:545:47: note: in expansion of macro 'NINA_GPIOIRQ'
 int SpiDrv::available() { return (digitalRead(NINA_GPIOIRQ) != LOW); }

**Comment by ricardoquesada** [comment]
Probably you are getting the `PIN_COUNT` error because the board selected in Arduino is not the "RP2040"... just go to Arduino -> Tools -> Board -> Arduino Mbed OS Nano Boards -> Arduino Nano RP2040.

If you are using a regular ESP32 kit, then you should not use Arduino... it just won't run [1]

So, if you ware using a regular ESP32 module, you should use the "bluepad32-unijoysticle" firmware as the base code... modify it as you wish... but you cannot use Arduino.
If you are using a Nano RP2040 then you are good... just select the "RP2040 board" in Arduino IDE


[1]: It is possible, but requires a loooot of work.

**Comment by Erebos84** [comment]
I have flashed the unicycle firmware to the ESP32.How can I use the API now?  Unlike "Bluepad32-Arduino" "Bluepad32" does not contain an example ("Gampepad.ino").

**Comment by ricardoquesada** [comment]
there is no example for the bluepad32-unijoysticle because it is supposed to be used only in the board Unijoysticle.

But you can program the ESP32 kit with the "bluepad32-unijoysticle" firmware and see the console.
The console should give you info regarding whether the Xbox Elite 2 gamepad was able to connect.

**Comment by Erebos84** [comment]
Hi,
i have now reflashed the precompiled bluepad32-unijoysticle (v2.2.1) on the ESP32. The Elite 2 controller does not pair with the ESP32. 
I have attached two logs to this post. The first one shows the pairing after the first boot of the ESP32. The second log shows the pairing attempt after a reboot of the ESP32. However, unfortunately I don't know enough about it to find the cause of the problem. Can you imagine what is the cause here?

(I have made a part of the MAC unrecognizable and shortened the first log a bit).

[first boot.log](https://github.com/ricardoquesada/bluepad32-arduino/files/7491438/first.boot.log)
[second boot.log](https://github.com/ricardoquesada/bluepad32-arduino/files/7491439/second.boot.log)

**Comment by ricardoquesada** [comment]
I took a look them, and I seems that everything is "OK"... I mean, the Xbox One S has similar issues... my guess is that the Xbox One S and the Xbox Elite share the same firmware (or might be 99% identical).
I'd just say: try again... sorry, don't have a better answer.

**Comment by Erebos84** [comment]
Does Bluepad32/btstack use Enhanced Retransmission Mode (ERTM)? In forums it is recommended to turn it off to be able to connect Xbox controllers with Linux.

**Comment by ricardoquesada** [comment]
good find.
btstack supports ERTM, but it seems it is disabled by default... but I'll do some tests with it to double-check it.

**Comment by ricardoquesada** [comment]
Although I don't have an Elite 2 to test, the new firmware (v3.6.0 and newer) supports BLE connections and with the Xbox firmware 5.x, it should work oK.

Please reopen it if it doesn't work. thanks
